version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Immunoglobin@812
    networks:
      - todo-network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: todo-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - todo-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - todo-network

volumes:
  mongodb_dev_data:

networks:
  todo-network:
    driver: bridge
